name: 'Sync to other hub (SSH URL and DELETE)'

on:
  delete:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'git@github.com:ttionya/Repository-Sync-Hub-Test.git'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'git@gitee.com:ttionya/Repository-Sync-Hub-Test.git'
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
