name: 'Sync to other hub (HTTP URL and PUSH)'

on:
  push:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          # Note: If your target repository is GitHub repository with HTTP URL, make sure use your own access token.
          token: ${{ secrets.HTTP_ACCESS_TOKEN }}
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'https://github.com/ttionya/Repository-Sync-Hub-Test.git'
          http_access_name: 'ttionya'
          http_access_token: ${{ secrets.HTTP_ACCESS_TOKEN }}

  gitee:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'https://gitee.com/ttionya/Repository-Sync-Hub-Test.git'
          http_access_name: 'ttionya'
          http_access_token: ${{ secrets.GITEE_HTTP_ACCESS_TOKEN }}
