name: 'Sync to other hub by schedule'

on:
  schedule:
    # see https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule for more information
    # run task at hour 0, 6, 12, 18 every day
    - cron: '0 * * * *'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'git@github.com:ttionya/Repository-Sync-Hub-Test.git'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  gitee:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Sync
        uses: ./
        with:
          target_repository: 'git@gitee.com:ttionya/Repository-Sync-Hub-Test.git'
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
